export const mockIngredients = [
    {
        id: "ing-1",
        name: "Bergamot Oil",
        casNumber: "8007-75-8",
        ifraCategory: "II",
        maxConcentration: 0.4,
        safetyNotes: "Phototoxic - avoid sun exposure after application",
        supplier: "Firmenich",
        cost: 45.5,
        odorProfile: "Fresh, citrusy, slightly floral with green facets",
        volatility: "top",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "ing-2",
        name: "Rose Oxide",
        casNumber: "16409-43-1",
        ifraCategory: "II",
        maxConcentration: 0.01,
        safetyNotes: "Potent allergen - use sparingly",
        supplier: "IFF",
        cost: 1250.0,
        odorProfile: "Fresh, green rose with metallic undertones",
        volatility: "middle",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "ing-3",
        name: "Ambroxan",
        casNumber: "6790-58-5",
        ifraCategory: "I",
        maxConcentration: 10.0,
        safetyNotes: "Generally safe - no restrictions",
        supplier: "Givaudan",
        cost: 85.75,
        odorProfile: "Warm, ambery, slightly marine with mineral facets",
        volatility: "base",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "ing-4",
        name: "Linalool",
        casNumber: "78-70-6",
        ifraCategory: "II",
        maxConcentration: 0.5,
        safetyNotes: "Common allergen - must be declared",
        supplier: "Symrise",
        cost: 32.2,
        odorProfile: "Fresh, floral, woody with citrus and spicy facets",
        volatility: "middle",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "ing-5",
        name: "Iso E Super",
        casNumber: "54464-57-2",
        ifraCategory: "I",
        maxConcentration: 21.4,
        safetyNotes: "Potential sensitizer at high concentrations",
        supplier: "IFF",
        cost: 48.9,
        odorProfile: "Smooth, woody, velvety with skin-like warmth",
        volatility: "base",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "ing-6",
        name: "Hedione",
        casNumber: "24851-98-7",
        ifraCategory: "II",
        maxConcentration: 1.0,
        safetyNotes: "Well tolerated - enhances other materials",
        supplier: "Firmenich",
        cost: 125.3,
        odorProfile: "Fresh, jasmine-like, transparent with radiant qualities",
        volatility: "middle",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
];

export const mockFormulae = [
    {
        id: "form-1",
        name: "Citrus Marine Accord",
        version: "2.1",
        description: "Fresh marine fragrance with bright citrus opening",
        createdBy: "1",
        status: "approved",
        totalConcentration: 15.0,
        batchSize: 1000.0,
        notes: "Excellent performance in hot weather. Consider reducing bergamot for winter version.",
        expirationDate: new Date("2025-06-15"),
        isCompliant: true,
        lastComplianceCheck: new Date("2024-01-10"),
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-20"),
    },
    {
        id: "form-2",
        name: "Woody Amber Complex",
        version: "1.8",
        description: "Sophisticated woody base with warm amber facets",
        createdBy: "1",
        status: "testing",
        totalConcentration: 22.5,
        batchSize: 500.0,
        notes: "Needs stability testing. Consider reducing Iso E Super concentration.",
        expirationDate: new Date("2024-12-30"),
        isCompliant: false,
        lastComplianceCheck: new Date("2024-01-18"),
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-01-18"),
    },
    {
        id: "form-3",
        name: "Floral Bouquet Premium",
        version: "3.0",
        description: "Luxurious floral composition with rose and jasmine",
        createdBy: "1",
        status: "draft",
        totalConcentration: 18.5,
        batchSize: 750.0,
        notes: "New formulation - awaiting ingredient approval",
        expirationDate: new Date("2025-03-20"),
        isCompliant: true,
        lastComplianceCheck: new Date("2024-01-19"),
        createdAt: new Date("2024-01-19"),
        updatedAt: new Date("2024-01-19"),
    },
];

export const mockFormulaIngredients = [
    // Citrus Marine Accord
    { id: "fi-1", formulaId: "form-1", ingredientId: "ing-1", percentage: 5.0, notes: "Opening note" },
    { id: "fi-2", formulaId: "form-1", ingredientId: "ing-3", percentage: 8.0, notes: "Marine base" },
    { id: "fi-3", formulaId: "form-1", ingredientId: "ing-4", percentage: 2.0, notes: "Fresh bridge" },

    // Woody Amber Complex
    { id: "fi-4", formulaId: "form-2", ingredientId: "ing-5", percentage: 15.0, notes: "Main woody note" },
    { id: "fi-5", formulaId: "form-2", ingredientId: "ing-3", percentage: 6.5, notes: "Amber warmth" },
    { id: "fi-6", formulaId: "form-2", ingredientId: "ing-4", percentage: 1.0, notes: "Softening agent" },

    // Floral Bouquet Premium
    { id: "fi-7", formulaId: "form-3", ingredientId: "ing-2", percentage: 0.5, notes: "Rose heart - use sparingly" },
    { id: "fi-8", formulaId: "form-3", ingredientId: "ing-6", percentage: 12.0, notes: "Jasmine transparency" },
    { id: "fi-9", formulaId: "form-3", ingredientId: "ing-4", percentage: 4.0, notes: "Floral support" },
    { id: "fi-10", formulaId: "form-3", ingredientId: "ing-1", percentage: 2.0, notes: "Citrus lift" },
];

export const mockDocuments = [
    {
        id: "doc-1",
        title: "IFRA Standards 50th Amendment",
        summarization:
            "Updated restrictions on various fragrance materials including new limits on rose oxide and bergamot oil in leave-on products...",
        type: "legal",
        uploadedBy: "1",
        fileUrl: "/documents/ifra-50th-amendment.pdf",
        metadata: { region: "global", authority: "IFRA", version: "50" },
        tags: ["ifra", "restrictions", "2024"],
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-05"),
    },
    {
        id: "doc-2",
        title: "EU Cosmetics Regulation Update Q1 2024",
        summarization:
            "New requirements for product information files and safety assessments for cosmetic products containing certain fragrance allergens...",
        type: "legal",
        uploadedBy: "1",
        fileUrl: "/documents/eu-cosmetics-q1-2024.pdf",
        metadata: { region: "EU", authority: "European Commission", quarter: "Q1-2024" },
        tags: ["eu", "cosmetics", "allergens", "pif"],
        createdAt: new Date("2024-01-12"),
        updatedAt: new Date("2024-01-12"),
    },
    {
        id: "doc-3",
        title: "Bergamot Oil Safety Data Sheet",
        summarization:
            "Comprehensive safety information for bergamot oil including handling, storage, and phototoxicity warnings...",
        type: "sds",
        uploadedBy: "1",
        fileUrl: "/documents/bergamot-oil-sds.pdf",
        metadata: { supplier: "Firmenich", version: "3.2", casNumber: "8007-75-8" },
        tags: ["sds", "bergamot", "phototoxic", "safety"],
        createdAt: new Date("2024-01-08"),
        updatedAt: new Date("2024-01-08"),
    },
];

export const mockComplianceRules = [
    {
        id: "comp-1",
        region: "EU",
        regulation: "IFRA-50",
        ingredientId: "ing-1",
        maxConcentration: 0.4,
        restrictions: "Maximum 0.4% in leave-on products due to phototoxicity",
        effectiveDate: new Date("2024-01-01"),
        expirationDate: null,
        documentId: "doc-1",
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-05"),
    },
    {
        id: "comp-2",
        region: "Global",
        regulation: "IFRA-50",
        ingredientId: "ing-2",
        maxConcentration: 0.01,
        restrictions: "Potent allergen - maximum 0.01% in all product categories",
        effectiveDate: new Date("2024-01-01"),
        expirationDate: null,
        documentId: "doc-1",
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-05"),
    },
    {
        id: "comp-3",
        region: "EU",
        regulation: "EU-CosReg",
        ingredientId: "ing-4",
        maxConcentration: 0.5,
        restrictions: "Must be declared on product label if >0.01%",
        effectiveDate: new Date("2024-01-15"),
        expirationDate: null,
        documentId: "doc-2",
        createdAt: new Date("2024-01-12"),
        updatedAt: new Date("2024-01-12"),
    },
];

export const mockFormulaTests = [
    {
        id: "test-1",
        formulaId: "form-1",
        testType: "stability",
        results: {
            temperature: "40°C",
            humidity: "75%",
            duration: "3 months",
            colorChange: "none",
            odorChange: "minimal",
            pHChange: "0.1",
            passed: true,
        },
        passed: true,
        testDate: new Date("2024-01-18"),
        testedBy: "1",
        notes: "Excellent stability profile. Approved for production.",
        createdAt: new Date("2024-01-18"),
        updatedAt: new Date("2024-01-18"),
    },
    {
        id: "test-2",
        formulaId: "form-2",
        testType: "compliance",
        results: {
            isoESuperConcentration: 15.0,
            maxAllowed: 21.4,
            roseOxideConcentration: 0.0,
            allergenCheck: "passed",
            overallCompliance: false,
            issues: ["Bergamot concentration exceeds IFRA limits"],
        },
        passed: false,
        testDate: new Date("2024-01-18"),
        testedBy: "1",
        notes: "Compliance check failed - bergamot oil concentration too high for EU market.",
        createdAt: new Date("2024-01-18"),
        updatedAt: new Date("2024-01-18"),
    },
];

export const mockAnalytics = {
    mostUsedIngredients: [
        { name: "Linalool", usage: 85, trend: "+12%" },
        { name: "Ambroxan", usage: 72, trend: "+8%" },
        { name: "Iso E Super", usage: 68, trend: "+15%" },
        { name: "Hedione", usage: 45, trend: "+22%" },
        { name: "Bergamot Oil", usage: 38, trend: "-5%" },
    ],
    expiringFormulae: [
        { name: "Woody Amber Complex", expirationDate: "2024-12-30", daysLeft: 45 },
        { name: "Summer Citrus Blend", expirationDate: "2025-02-15", daysLeft: 92 },
        { name: "Oriental Spice Mix", expirationDate: "2025-03-10", daysLeft: 115 },
    ],
    complianceAlerts: [
        { formula: "Woody Amber Complex", issue: "Bergamot exceeds IFRA limits", severity: "high" },
        { formula: "Rose Garden Accord", issue: "Rose oxide concentration review needed", severity: "medium" },
        { formula: "Citrus Burst V2", issue: "Allergen declaration missing", severity: "low" },
    ],
    costAnalysis: {
        totalFormulaCost: 15420.75,
        averageCostPerFormula: 5140.25,
        mostExpensiveIngredient: "Rose Oxide",
        costOptimizationOpportunities: 3,
    },
};
